//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetStudy.WebService.Test.WCFConsoleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFConsoleService.IMathService")]
    public interface IMathService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Plus", ReplyAction="http://tempuri.org/IMathService/PlusResponse")]
        int Plus(int i, int j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathService/Plus", ReplyAction="http://tempuri.org/IMathService/PlusResponse")]
        System.Threading.Tasks.Task<int> PlusAsync(int i, int j);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathServiceChannel : DotNetStudy.WebService.Test.WCFConsoleService.IMathService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathServiceClient : System.ServiceModel.ClientBase<DotNetStudy.WebService.Test.WCFConsoleService.IMathService>, DotNetStudy.WebService.Test.WCFConsoleService.IMathService {
        
        public MathServiceClient() {
        }
        
        public MathServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Plus(int i, int j) {
            return base.Channel.Plus(i, j);
        }
        
        public System.Threading.Tasks.Task<int> PlusAsync(int i, int j) {
            return base.Channel.PlusAsync(i, j);
        }
    }
}
